//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelCategory
    {
        public int ModelID { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
