//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public int ModelID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public int ProductStatusID { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ModelCategory ModelCategory { get; set; }
        public virtual ProductStatus ProductStatus { get; set; }
    }
}
